# backend/app/services/mock_data.py
# In-memory mock database for demonstration without a real DB connection.

MOCK_SECTORS = [
    {
        "id": 1,
        "lte_site_id": "SITE_001",
        "sector_id": "S1",
        "frequency_ghz": 1.8,
        "lte_band": "Band 3",
        "duplex_mode": "FDD",
        "antenna_gain": 17.0,
        "antenna_height": 30.0,
        "tower_height": 35.0,
        "azimuth": 0.0,
        "mech_tilt": 2.0,
        "elec_tilt": 6.0,
        "address": "123 Main St, Big City, Capital District",
        "district": "Capital District",
        "tehsil": "Big City",
        "town": "Downtown"
    },
    {
        "id": 2,
        "lte_site_id": "SITE_001",
        "sector_id": "S2",
        "frequency_ghz": 1.8,
        "lte_band": "Band 3",
        "duplex_mode": "FDD",
        "antenna_gain": 17.0,
        "antenna_height": 30.0,
        "tower_height": 35.0,
        "azimuth": 120.0,
        "mech_tilt": 2.0,
        "elec_tilt": 6.0,
        "address": "123 Main St, Big City, Capital District",
        "district": "Capital District",
        "tehsil": "Big City",
        "town": "Downtown"
    },
    {
        "id": 3,
        "lte_site_id": "SITE_001",
        "sector_id": "S3",
        "frequency_ghz": 2.3,
        "lte_band": "Band 40",
        "duplex_mode": "TDD",
        "antenna_gain": 18.0,
        "antenna_height": 30.0,
        "tower_height": 35.0,
        "azimuth": 240.0,
        "mech_tilt": 2.0,
        "elec_tilt": 6.0,
        "address": "123 Main St, Big City, Capital District",
        "district": "Capital District",
        "tehsil": "Big City",
        "town": "Downtown"
    },
    {
        "id": 4,
        "lte_site_id": "SITE_002",
        "sector_id": "S1",
        "frequency_ghz": 0.9,
        "lte_band": "Band 8",
        "duplex_mode": "FDD",
        "antenna_gain": 17.0,
        "antenna_height": 45.0,
        "tower_height": 50.0,
        "azimuth": 60.0,
        "mech_tilt": 3.0,
        "elec_tilt": 8.0,
        "address": "456 Side Ave, Small Town, Rural District",
        "district": "Rural District",
        "tehsil": "Small Town",
        "town": "Old Town"
    },
    {
        "id": 5,
        "lte_site_id": "SITE_002",
        "sector_id": "S2",
        "frequency_ghz": 2.6,
        "lte_band": "Band 7",
        "duplex_mode": "FDD",
        "antenna_gain": 18.0,
        "antenna_height": 45.0,
        "tower_height": 50.0,
        "azimuth": 180.0,
        "mech_tilt": 3.0,
        "elec_tilt": 8.0,
        "address": "456 Side Ave, Small Town, Rural District",
        "district": "Rural District",
        "tehsil": "Small Town",
        "town": "Old Town"
    },
    {
        "id": 6,
        "lte_site_id": "SITE_003",
        "sector_id": "A",
        "frequency_ghz": 1.8,
        "lte_band": "Band 3",
        "duplex_mode": "FDD",
        "antenna_gain": 17.5,
        "antenna_height": 25.0,
        "tower_height": 30.0,
        "azimuth": 30.0,
        "mech_tilt": 4.0,
        "elec_tilt": 5.0,
        "address": "789 County Road, Farm Town, Rural District",
        "district": "Rural District",
        "tehsil": "Farm Town",
        "town": "Countryside"
    },
    {
        "id": 7,
        "lte_site_id": "SITE_003",
        "sector_id": "B",
        "frequency_ghz": 1.8,
        "lte_band": "Band 3",
        "duplex_mode": "FDD",
        "antenna_gain": 17.5,
        "antenna_height": 25.0,
        "tower_height": 30.0,
        "azimuth": 150.0,
        "mech_tilt": 4.0,
        "elec_tilt": 5.0,
        "address": "789 County Road, Farm Town, Rural District",
        "district": "Rural District",
        "tehsil": "Farm Town",
        "town": "Countryside"
    },
    {
        "id": 8,
        "lte_site_id": "SITE_003",
        "sector_id": "C",
        "frequency_ghz": 1.8,
        "lte_band": "Band 3",
        "duplex_mode": "FDD",
        "antenna_gain": 17.5,
        "antenna_height": 28.0, # Mismatch for antenna audit
        "tower_height": 30.0,
        "azimuth": 270.0,
        "mech_tilt": 4.0,
        "elec_tilt": 5.0,
        "address": "789 County Road, Farm Town, Rural District",
        "district": "Rural District",
        "tehsil": "Farm Town",
        "town": "Countryside"
    }
]
